version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsb_app
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=development
      - FLAG=FeDEX
    restart: unless-stopped
